### ISSUE TITLE
Please allow the struct tag to be changed to "json"

### ISSUE THREAD

**Issue by scudette** [go-yaml/yaml#424] opened 2019-01-03 14:11 UTC
I find no way to tell the yaml package to just use "json" as the tag. This is quite unfortunate because I have no control over the generated structs (which are actually produced by the protobuf compiler and get json tags by default) but I need to parse these from YAML.

I would be rather trivial to provide an option as the name of the tag to use. TBH the state of go right now is that most people add json tags to their structs but not yaml tags. It is quite pointless to add multiple tags and often we have no control over the structs (because they came from someone else's code).

This has been hacked around in the past using e.g. github.com/ghodss/yaml but it is fragile and hacky. The easier solution for us right now is to just fork this repo and do a 3 char change :-).

**Comment by andrewpillar** [comment] 2019-01-03 14:31
This seems pretty nonsensical to me. With the `yaml` tags you get clarity over the how the given type will be marshalled, and unmarshalled.

>TBH the state of go right now is that most people add json tags to their structs but not yaml tags.

This seems like a rather narrow minded thing to say, I can think of two projects that introduce additional struct tags for the marshalling and unmarshalling of data. One of these is [schema](https://github.com/gorilla/schema) which uses the `schema` tag for parsing HTTP POST form data, and the other is [sqlx](https://github.com/jmoiron/sqlx) that uses the `db` tag for parsing rows from an SQL database.

I will re-iterate what I previously said, though I am not the maintainer, or even a contributor to this project, the `yaml` tag makes sense, it provides clarity. When I read a struct and notice the `yaml` tags I will understand that it will either be turned into YAML at some point in the program, or be created from some YAML input.

>This is quite unfortunate because I have no control over the generated structs (which are actually produced by the protobuf compiler and get json tags by default) but I need to parse these from YAML.

If you're working with another open source library that is generating these `json` tagged structs then why not open an issue there? Or better yet fork it, and try and implement a solution whereby the generated structs are tagged appropriately for your use case.

**Comment by scudette** [comment] 2019-01-03 16:11
I struggle to think of a practical reason why I would like to name a field something different in YAML vs JSON vs schema or any other serialization. It actually seems like a terrible idea to tie the field name to a serialization format from a documentation and usability point of view.

Usually the tag naming mechanism is used to work around Golang's mangling of names. Unfortunately we are stuck with Golang's tag mechanism which has to go in the file which defines the structs in the first place so there is no way to change it after the fact from an external file. Most of the time the tag specifies that to de-mangle SomeField from the go struct you would call it some_field in the yaml/json whatever.

Regarding your suggestion of opening an issue with protobuf to ask them to add yaml tags. You realize this will just not work if everyone that had a pet serialization format added their unique tags to existing structs - this just does not scale. You would end up with a dozen tags all the same anyway because again, there just isn't a sane reason why you would want to be inconsistent with demangling of names.

To understand more of the rational please see http://ghodss.com/2014/the-right-way-to-handle-yaml-in-golang/ who explains it pretty well, although his solution is hacky and does not work too well actually. In particular we lose sanitation with his solution because invalid fields get dropped off in the round trip from yaml to json and then being parsed with json unmarshal.

Anyway for us we fixed it by forking the project and changing a single line and this saved us a bunch of work so we are good but obviously we are not the only ones who encountered this issue (https://github.com/Velocidex/yaml).

**Comment by andrewpillar** [comment] 2019-01-03 16:34
>It actually seems like a terrible idea to tie the field name to a serialization format from a documentation and usability point of view.

Honestly, it actually seems like a pretty good idea in my mind, considering the `encoding/xml` package from the standard library does this too with the `xml` tag.

>Regarding your suggestion of opening an issue with protobuf to ask them to add yaml tags. You realize this will just not work if everyone that had a pet serialization format added their unique tags to existing structs - this just does not scale.

I think that decision could be left at the discretion fo the maintainers of the library, and entirely depends on how the solution is implemented.

The article you linked mainly hits on the points of incorrect implementations of the `Unmarshal`, and `Marshal` functions, since the article is 4 years old I think it would be reasonable to assume that these issues are no longer a concern, correct me if I'm wrong.

It seems to me that the main reason you're doing this is because of this generated code from a protobuf which expects to be marshalled/unmarshalled to/from JSON, in which case why not just use JSON and furlough YAML entirely?

**Comment by scudette** [comment] 2019-01-03 17:20
In my application I use yaml as a configuration language (to let people type it) and then I parse it into a protobuf. I also send the same protobufs over REST to JS app so I need the same things in json (luckily no xml yet!). Thanks for reinforcing my point with the xml library which does the same thing again. So now I would have to add the following tags to my structs:

```
type foobar struct {
   MyFieldName string `json:"my_field_name" xml:"my_field_name" yaml:"my_field_name" toml:"my_field_name"`
}
```
You realize how silly this is right? 

This is bad enough for my code, but imagine if I am writing a library which I want people to use - e.g. `gopsutil` I am exporting instances of my struct (say I have Process struct for process listings) and I really have no idea what people would want to do with them (I am a library after all). If I end up adding  a tag for every user it just gets ridiculous, but if I dont the user has to redefine all of my structs, then copy all the fields over - they cant just feed the struct I give them to say a yaml marshal because it will come up with incorrect field names.

They might end up just relying on the default name demangling, but then there is inconsistency between the field encoded in json and yaml since json tag will be defined but for other serializations it would be the default demangling. This can lead to a lot of subtle bugs also because people forget. We just had a bug where a protobuf field was called "logging" but json tag said "Logging" which means the json and golang is the same in this case. But when we used yaml it just dropped the field "Logging" because it did not see the json tag and expected it to be called "logging" - so confusing! 

Since we use yaml as the configuration format we really need to make sure there is a correspondence between the yaml field names and the protobuf field names (the .proto **is** the api documentation). So we just had a case where a use just could not figure out what to type in the yaml file. The field name was a word with an underscore (say foo_bar) and of course due to Golang's mangling this ends up being FooBar in the go struct but the protobuf compiler adds a json tag to convert FooBar to foo_bar in json which is the usual convention.

But we were parsing the config file from yaml and used strict unmarshal so the user tried foo_bar (like the api docs said) but it was rejected they tried FooBar which was also rejected. This is very confusing.

It turns out that when yaml does the default demangling it uses an unusual algorithm:
https://github.com/go-yaml/yaml/blob/v2/yaml.go#L395

```
info.Key = strings.ToLower(field.Name)
```

so FooBar becomes foobar (i.e. the _ seems to get dropped). This is actually different from json's default demangling too. So now the user really has no idea what to type in the configuration file. It seems random and they have a bad experience.

**Comment by andrewpillar** [comment] 2019-01-03 17:32
>This is bad enough for my code, but imagine if I am writing a library which I want people to use - e.g. gopsutil I am exporting instances of my struct (say I have Process struct for process listings) and I really have no idea what people would want to do with them (I am a library after all). If I end up adding a tag for every user it just gets ridiculous, but if I dont the user has to redefine all of my structs, then copy all the fields over - they cant just feed the struct I give them to say a yaml marshal because it will come up with incorrect field names.

Or just not bother with that, and let the user's of your library handle the marshalling/unmarshalling themselves. Like you said you have no idea how the user intends on using the data structures, so why enforce a way upon them?

Anyway, my point boils down to this: the `yaml`, `json`, `xml` tags allow for clarity, sure it's verbose, but then again Go is a fairly verbose, and brutalist language. I remain unconvinced by your argument, besides, you've already forked the library and applied the necessary changes to solve your problem so why not continue using that, and merge in any changes from the upstream as you see fit?

And to add on to your previous point:

>It actually seems like a terrible idea to tie the field name to a serialization format from a documentation and usability point of view.

This makes sense to me in my mind. Don't you want understanding over how a field will be serialized between different serialization means, and how that field would map?

**Comment by scudette** [comment] 2019-01-04 01:54
> Or just not bother with that, and let the user's of your library handle the marshalling/unmarshalling
> themselves. Like you said you have no idea how the user intends on using the data structures, so why 
> enforce a way upon them?

I really dont understand what you are saying here. The user of my library has no choice but to ask me to cater for them and the way they want to use my exported struct. They literally **can't** control how the struct is to be serialized without making their own struct and copying my struct into theirs. My suggestion is exactly to allow them to control it. For example if they can pass an arg to yaml.Marshal() to use json tags instead then they could just do what they want with it.

Look I know its not yaml's fault - this is clearly a wart in Golang. Obviously confounding the way something is to be used (i.e. how it will be serialized) with the way it is defined (struct definition) is a really bad idea. Like it or not, json seems to be the default serialization out there and everyone adds json tags at least. I am just suggesting that yaml just go with that if yaml specific tags are not defined.

You can take my feedback about yaml's non standard default field demangling algorithm as a possible bug report or issue. When we have to fall back on default name mangling then the different libraries' approaches are very confusing to users (which is why we never do and always add at least json tags).

The issue here is that yaml's default is to lower case go's field name, and json's default is to just use go's field name. This is confusing inconsistent and has no logical reason not to mention that the yaml scheme is lossy (i.e. round tripping through yaml **requires** yaml tags because the default scheme is buggy and will break).

So far the only reasons you gave are: 
1. Everyone else is doing the same so we should.
2. It provides more clarity.

The first argument does not actually address the concern. The second is also unclear - I just demonstrated to you that this approach causes confusion and that there is no easy way for people to work around it (well other than fork the project and change a single line).

As you say this is opensource code. Please dont get the impression that I am ungrateful for the project - of course I can fork it to solve my specific issue. I am just filing this issue to provide feedback on a real life problem we have with the library.  The maintainers of yaml can take this feedback on board or ignore it.

Please feel free to close the issue with "Wont fix". This is just feedback and like I said its probably a wider problem with Go's serialization tied to field tags and not specifically confined to yaml.

**Comment by tespeleta** [comment] 2019-05-23 08:11
I think the problem is with protobuf, not with yaml. There is a long standing issue in protobuf about having custom tags in generated structs: https://github.com/golang/protobuf/issues/52. I have to say is most unfortunate that there is still no answer to that but creating a fork or a plugin.
This leads to fragmentation, like this fork which I think is quite widespread: https://github.com/gogo/protobuf

**Comment by wxdao** [comment] 2019-07-09 10:29
I agree that having yaml tag provides more clarity. However, I think it's also reasonable to fallback to take the value from json tag when a struct field has no yaml tag, isn't it? Don't forget that yaml is a superset of json.

**Comment by laverya** [comment] 2019-07-10 18:00
Or, better still, provide the ability to specify what tag to use - or perhaps even what set of tags to use. Changing the default to "yaml, and if not present json" may break some things, but providing the option shouldn't break anything that I'm aware of.

**Comment by msteffen** [comment] 2019-10-02 08:24
My company, Pachyderm, is in a similar situation (we parse configs into protobuf-generated structs, and therefore can't change the generated struct tags to be `yaml:` instead of `json:`). I would be willing to implement this feature if the maintainers of `go-yaml` are accepting outside PRs

**Comment by scudette** [comment] 2019-10-02 10:15
TBH I consider YAML pretty much feature complete for our use case (parsing config files to/from protobufs) so I just forked it and completely forgot about this issue. I am OK with not getting the latest patches and bugfixes in the yaml library as long as our build is stable. You could just fix this issue by using https://github.com/Velocidex/yaml instead which just uses JSON tags instead.

It really does not make sense to me that each serialization format needs to be explicitly specified in a tag but this is a fight that is not really worth pursuing :-).

**Comment by theriverman** [comment] 2019-12-13 16:25
I'd like to 👍 this feature request.
**Here's my short use case:**
  * I'm using a 3rd party go package to send/get data from JIRA.
  * All of the struct tags are defined for `json` in this 3rd party module, no `yaml` tags.
This is totally reasonable, because JIRA talks JSON over REST, right?

However, I want to give my users the flexibility to provide their configuration either in YAML or JSON.
Portions of their provided data (if it's JSON) is Marshalled directly into these 3rd party structs.

If they want to provide their input in YAML, there's no way to do that without creating struct duplicates in the code by copy-pasting the original struct definitions from the 3rd party module and manually adding the yaml tags for each field.

Having the option in the `yaml` package to define the desired file format would be a huge help for edge cases like ours. It would remain robust, yet very simple. To avoid breaking legacy, the introduction of two new functions seems to be the most feasible way to enable flexible serialization.

Here's a sketchy interface proposal:
```go
func MarshalFlex(in interface{}, format string) (out []byte, err error)
```
```go
func UnmarshalFlex(in []byte, out interface{}, format string) (err error)
```

Please consider making this yaml package a bit more flexible!

**Comment by disposedtrolley** [comment] 2019-12-13 21:44
We’ve had a similar use case to @theriverman which would’ve benefited hugely from more flexibility in the yaml package :) 

Our tool parses OpenAPI files using a third party library, which can be written in JSON or YAML. The library caters for both formats by converting YAML to JSON first, then in marshaling the JSON into various structs which contain only `json` tags.

We had an edge case which required direct serialisation and deserialisation into YAML due to some quirks with the YAML to JSON conversion, and were unable to use this library since none of the types in the third party library had `yaml` tags. Fortunately for us, the author was happy to accept PRs, so we resolved this issue by adding `yaml` tags to every field of every struct, however this was still quite a painful process. I can see cases where enhancements can’t be made to critical third party libraries, so they must either be forked or their structs must be duplicated to support YAML.

**Comment by bpeake-illuscio** [comment] 2019-12-27 10:12
I want to throw in my two cents that it would be really nice to define an arbitrary tag to use. It's really inane that to allow for multiple serialization formats you end up with a tag like:


```
type Wizard stuct {
    Name string `json:"name" bson:"name" xml:"name" yaml:"name" proto:"name" toml:"name"` ....
}
```


I would really love to see more serialization libraries allow configuration on the tag to be used. If every lib allowed it, you could just do something like:

```
type Wizard struct {
    Name string `serialized:"name"`
}
```

And be done with it. As is, to add a new serialization format, you have to go through and add a tag to EVERY object field, which is non-trivial for a lot of projects. It also helps make much cleaner code.

**Comment by bpeake-illuscio** [comment] 2019-12-30 20:10
To add further to this:

I think the current idiomatic solution for GO serialization libraries heightens the chance of uncaught and possibly subtle bugs for libraries who want to support multiple serialization formats of their objects.

Go does not check these tags at compile-time in any way, and I imagine that many coders like myself copy-paste the long list of tags. If you accidentally skip over ONE tag, then you have a single serialization format which may contain the incorrect key.

Likewise, if you decide to refactor a field name, you have to remember to update every tag. If you are working with large data structures, these bugs might slip through.

This of course, is not the MAIN reason to add a custom tag option, but I think it is ANOTHER reason.

**Comment by lietu** [comment] 2020-03-14 10:43
Sure sounds like that instead of changing the various libraries to pretend they're JSON parsers, you want the language-wide standard to be changed to include something like a `*` as default for all.

```golang
type Foo struct {
  Field string `*:"field_name" xml:"fieldName"`
}
```

I wouldn't mind seeing a change like that, but having a yaml library significantly deviate from the expected and widespread standard of using its own clear tag and instead using the json one would be incredibly surprising to me as a developer, and the principle of least astonishment is a very important one to follow.

**Comment by scudette** [comment] 2020-03-14 12:17
It won't be surprising to you if you had to explicitly change the
serialization tag name when setting up the marshaller. This proposal is
about making the tag name configurable, the default can be whatever makes
sense even yaml, but we need to change it in some cases because it is the
path of least resistance for interoperability. As it is we need to maintain
a fork of this repo (which has a one line change) so it's more work to keep
up to date on bug fixes etc (although in practice this has not been a huge
problem for us).

**Comment by lietu** [comment] 2020-03-14 12:56
Sounds like you're talking about your personal preference in a very specific use-case, which is not what should typically guide the development of general purpose libraries. If you have a specific need like that, maybe forking is the right way, or maybe you should e.g. consider writing some tools to do automatic code generation.

If someone builds a library, and in that library decides that they use this new feature on data structures I give it, I will be very surprised when it's actually using the `json` tags instead of the `yaml` tags or similar. I would not be surprised if it used a `default`, `*`, or similar.

Also this `default`, `*`, etc. can be applied to other libraries and uses throughout the Go ecosystem as well, with less changes to any APIs.

**Comment by scudette** [comment] 2020-03-14 13:04
Clearly this is not confined to my personal preference as evidenced by this long thread :-). I believe the motivations for this bug have been explained clearly so far by many users as as myself, and if you can't see the need for them than there is little more to add :-). 

I am glad I was reminded of this bug though because now I found out about https://github.com/goccy/go-yaml which seems to automatically support json tags if they are present and yaml tags are not. I think that will work well for my use case, and seems like a sensible approach to me.

**Comment by niemeyer** [comment] 2020-03-14 13:05
I can understand the desire, but JSON is not YAML, and the json package is not the yaml package either. There are several things that one needs to do to make such a parser work correctly and as expected, and that's far from being a one line change. I'm not keen on having to forever maintain all of the json package behavior inside the yaml package, and all the awkward edge cases that this will create.

With that said, if you want the behavior of the json package as a YAML file, it's trivial to use the json package to create a generic map of the data, and then ask the yaml package to marshal it out for you.

I apologize for not having better news on that front. I'll close this ticket on that basis.

**Closed as completed by niemeyer** 2020-03-14 13:05 UTC

**Comment by scudette** [comment] 2020-03-14 13:07
No worries @niemeyer but this is not what this bug is about at all. Please read the above thread more carefully - I do not want to use the yaml package to parse json files!

**Comment by niemeyer** [comment] 2020-03-14 13:12
I understand exactly what your desire is, and I have empathy for it. I just won't be able to help in this case. If you want to decode a structure that has "json" struct tags and which you cannot touch, the best solution is to use the json package. You can then optionally hand the decoded data to the yaml package.

**Comment by scudette** [comment] 2020-03-14 14:13
Ah thanks I understand the workaround you suggest. Sadly this won't work for us because, as I mentioned, we use YAML as a config file format and it is important to make sure that we return accurate error information if the user messes up the config. This hack will cause error line numbers to be inaccurate and will just confuse users. We also really need to use UnmarshalStrict() for this reason too and UnmarshalStrict() does not work unless we unmarshal into a struct (since it can not know what fields are valid in a map).

**Comment by phillip-elm** [comment] 2020-05-15 23:58
I'm a bit late to this - but I wonder if a feature where one value could be assigned to multiple tags is something that would work as a middle-ground?

```go
type Foo struct {
  Bar string `json,yaml:"bar"`
  Baz uint64 `json,yaml:"baz" xml:"the_cooler_baz"`
}
```

That would probably be a feature request for the `reflect` package, but it would also seem to solve the issue while requiring no changes from existing packages like `encoding/json` and go-yaml.

**Comment by pbarker** [comment] 2020-08-10 20:44
YAML is a superset of JSON, for simplicities sake using the JSON tag is the YAML one isn't present seems like a very reasonable idea. 

I hope the author reconsiders this needless rigidity.

**Comment by gophobic** [comment] 2020-08-25 01:12
according to the go team reusing json tags in yaml is totally nonsensical but writing 3 deep level prone error loops just to reinvent map, filter, etc.. from scratch, using int constants as enums, allowing null access is totally sensical

**Comment by niemeyer** [comment] 2020-08-25 16:40
@gophobic This isn't the place for rants.

**Comment by kirillmakhonin** [comment] 2020-08-25 17:52
@niemeyer, let me put my two cents in this thread.
Example of what we've faced with:
We have an application with a complex config structure. We allow users to store config in the YAML or JSON formats. Without ability to customize name of tag during marshal / unmarshal procedure execution we have to write something like that
```
type ConfigSubsystemX struct {
   DbUrl string `json:"db_url" yaml:"db_url"`
   ...
}
```
instead of
```
type ConfigSubsystemX struct {
   DbUrl string `field_name:"db_url"`
   ...
}
```

I understand that if somebody uses standard library it should be a problem and I really do not understand _why we can not add additional function like `MarshalWithOptions` or smth like that._

**Comment by niemeyer** [comment] 2020-08-25 17:56
We will certainly have something along the lines of MarshalWithOptions.. this is already in progress in a different issue and PR, and I'm behind on getting it in.

That's unrelated to supporting compatibility across the two marshalers, though. Their behavior is not the same today, and it's not just a matter of reading it from a different tag and it'll all be alright. If you want to dig in, feel free to try to run the json test suite with the yaml marshaler, while simply hacking the tag, and let us know of your experience.

**Comment by narisongdev** [comment] 2021-02-21 16:31
I think this is a reasonable feature and it can be supported by exposing the `Tag` variable. I implemented it in this [fork](https://github.com/narisongdev/yaml). It's just one line of change. It supports any type of Tag, with "yaml" as the default.

**Comment by laverya** [comment] 2021-02-21 16:41
Unfortunately that's a global, and so will probably break things if there are multiple users of this yaml library. IMO it would have to be exposed as a configuration option on an encoder/decoder. (You might have a subdependency that only has yaml tags, for instance)

**Comment by Fryuni** [comment] 2022-08-03 03:02
Adding to this, [mapstructure](https://github.com/mitchellh/mapstructure) allows the tag to be set on each operation, defaulting to the name of the library. The same could be done here (and in other serialization libraries).
It seems like the encouraged Go way for serialization, which is quite evident in every serialization lib in go that I know of, is not for larger compatibility but to answer with "Let every user redo everything themselves to explicit use my lib. They must show the proper commitment and pay the cost".

**Comment by ivanjaros** [comment] 2022-10-11 09:24
+1 for this. falling back to json tags when yaml tags are not present is a no-brainer that shouldn't even be argued.

**Comment by thallgren** [comment] 2022-11-07 14:24
JSON is a subset of YAML, so all JSON code is parseable with this package. With that in mind, it's hard to understand the argument against falling back to json struct tags.

I know the sigs.k8s.io/yaml does, but this package has better parser support with proper nodes etc., so I don't want to switch.

Please reconsider this?

**Comment by marcozac** [comment] 2023-01-04 18:18
If there is no other choice, a (very expensive) workaround is to use `reflect` to copy the json tags.

The same code below is in this [gist](https://gist.github.com/marcozac/201c380a07337956464c81dc2846d651). There is also a simple test, but it's strongly recommended to do more tests before using it.

```go
import (
	"reflect"

	"gopkg.in/yaml.v3"
)

func Unmarshal(data []byte, out any) error {
	pv := reflect.ValueOf(out)
	nv := reflect.NewAt(conv(reflect.Indirect(pv).Type()), pv.UnsafePointer())

	err := yaml.Unmarshal(data, nv.Interface())
	if err != nil {
		return err
	}

	return nil
}

func conv(t reflect.Type) reflect.Type {
	l := t.NumField()
	sf := make([]reflect.StructField, l)

	var tagVal string
	var ok bool

	for i := 0; i < l; i++ {
		sf[i] = t.Field(i)

		if sf[i].Type.Kind().String() == "struct" {
			sf[i].Type = conv(sf[i].Type)
		}

		_, ok = sf[i].Tag.Lookup("yaml") // skip yaml tag
		if ok {
			continue
		}

		tagVal, ok = sf[i].Tag.Lookup("json")
		if ok {
			sf[i].Tag = sf[i].Tag + ` yaml:"` + reflect.StructTag(tagVal) + `"`
		}
	}

	return reflect.StructOf(sf)
}
```

**Comment by ivanjaros** [comment] 2023-01-04 18:31
or simply use[ github.com/goccy/go-yaml ](https://github.com/goccy/go-yaml) and forget about this library altogether

**Comment by dee-kryvenko** [comment] 2024-03-21 05:06
This is so stubborn to refuse to do it. I understand if you were asked to support `toml` or `protobuf` tags, but YAML is literally a superset of JSON. By the very standard, any valid JSON must be a valid YAML also. In the spirit of that standard, one can make an argument that things like json tags in Go should also be respected by any yaml library. Let's just list a few very small projects:

- https://github.com/kubernetes/api/blob/v0.29.3/core/v1/types.go#L3501 `json:"containers"`, but not `yaml:"containers"`
- https://github.com/argoproj/argo-cd/blob/v2.10.4/pkg/apis/application/v1alpha1/types.go#L65 `json:"source,omitempty"`, but not `yaml:"source,omitempty"`
- https://github.com/hashicorp/terraform/blob/v1.7.5/internal/command/jsonplan/resource.go#L15 `json:"address,omitempty"`, but not `yaml:"address,omitempty"`
- https://github.com/helm/helm/blob/v3.14.3/pkg/release/release.go#L24 `json:"name,omitempty"`, but not `yaml:"name,omitempty"`
- https://github.com/containerd/containerd/blob/v1.7.14/images/image.go#L393 `json:"fsLayers,omitempty"`, but not `yaml:"fsLayers,omitempty"`
- https://github.com/moby/moby/blob/v26.0.0/image/image.go#L34 `json:"id,omitempty"`, but not `yaml:"id,omitempty"`

Shall I continue? This is a common understanding in the world that YAML is a superset of JSON, and if you'll keep going against the world - well, the world will keep choosing `sigs.k8s.io/yaml`, `github.com/goccy/go-yaml` and other alternatives.

Good luck with your project.

**Comment by roccolangeweg** [comment] 2024-04-05 21:06
Our project needs to generate Kubernetes YAMLs files from `k8s.io/apimachinery/pkg/apis` package and was also looking for a way to allow us to configure the tag-name from the default "yaml" to any other value (in our case "json").

Very sad to see this very long issue and no resolution on making it configurable, but also happy that this issue does have a link to another package that fits our use case.

I understand you don't want to have your package dependent in any way with the json package. But at least allow your users to overwrite your defaults.
