### ISSUE TITLE
Anything the community can do to help maintain this library?

### ISSUE THREAD

**Issue by tonglil** [go-yaml/yaml#261] opened 2017-05-11 21:41 UTC
This yaml library seems to be the definitely library depended on by many Go packages.

Is there something the community can do to help merge fixes to various identified and confirmed issues @niemeyer?

**Comment by kevinburke** [comment] 2017-05-17 01:26
triaging bugs would probably help, indicating issues that should be closed would help, performing code reviews on open issues would probably help

**Comment by niemeyer** [comment] 2017-05-17 13:31
Several weeks back I had a conversation with @rogpeppe and we agreed he'd allocate some of his time to keeping this library up-to-date and well taken care of. This seems to be taking slightly more time than expected to happen, though.

@rogpeppe Do you have any news there?

**Comment by nmiyake** [comment] 2017-05-18 22:07
Happy to do a pass on some of these things -- we make extensive use of this library and find it very valuable and would love to see some more movement on some of the open issues/PRs.

What's the best way to flag issues that should be closed? Is there someone I can `@` to flag to who can close out things that are stale/resolved?

**Comment by balanatarajan** [comment] 2017-05-29 15:47
@niemeyer What is the expected commitment for maintaining this? I can see whether someone in my team would be willing to help as well

**Comment by lox** [comment] 2018-03-09 05:24
I'm happy to assist to. We make heavy use of it too.

**Comment by niemeyer** [comment] 2018-03-09 16:09
@lox Help is always appreciated, and that's true of anything I have some involved on.

The best way to help is to engage and perform tasks that other long term maintainers would otherwise have to sit down and dedicate spans of time to do. Once the PR is ready for merging, it's easy to click on the button.

For example, I see you have interest on #220. This PR has a large number of changes that are completely unrelated to fixing a bug. It doesn't even describe what the problem is, although I can see that there's clearly a problem and that other people agree, which means we want to merge _something._ So, valuable work includes:

* Reviewing code, looking for potential issues
* Separating related changes from unrelated changes
* Ensuring all the changes are well tested
* Ensuring we're following established conventions from Go
* _Finding_ what the conventions are in the first place (no matter how experienced, following patterns involves looking for them too)
* Recommending actions (closing bugs)

Hope that helps a bit.

As a side note, I'm working on yaml.v3 right now. Some major improvements coming.

**Closed as completed by niemeyer** 2018-03-09 16:09 UTC

**Comment by lox** [comment] 2018-03-10 06:13
I'll see what I can do!

**Comment by niemeyer** [comment] 2018-03-10 10:19
Thanks @lox, and welcome.
