### ISSUE TITLE
Handling of time.Time is not symmetrical

### ISSUE THREAD

**Issue by tchap** [go-yaml/yaml#82] opened 2015-02-17 11:45 UTC
I haven't dived into `go-yaml` sources too much, but it appears to me that when I marshal `time.Time`, it uses `Time.String` to encode the field. Then it uses `Time.UnmarshalText` to decode it. But these methods use different formats and the whole thing fails with something like `parsing time "2015-02-17T12:15:23+01:00" as "2006-01-02 15:04:05.999999999 -0700 MST": cannot parse "T12:15:23+01:00" as " "`, so I ended up wrapping `time.Time` like

``` go
type Time time.Time

func (t Time) String() string {
    raw, err := time.Time(t).MarshalText()
    if err != nil {
        panic(err)
    }   
    return string(raw)
}
```

Now it works just fine.

**Comment by niemeyer** [comment] 2015-02-24 18:27
Can you please provide a self-contained snippet demonstrating the problem? It seems to work fine here, and I just added a couple of tests in 50f7813 which confirm it. The format may not be the proper one since yaml has a well-defined format for timestamps, but this at least confirms that the current behavior which happens naturally due to the support of text marshaling interfaces, is basically sane.

I'm closing this based on the above tests, but please feel free to reopen with more details and a reproducer.

**Comment by tchap** [comment] 2015-02-24 21:23
The funny part is that the test passes or fails depending on the time zone :D

**Comment by tchap** [comment] 2015-02-24 21:33
So why is it so that when I marshal `time.Now()` I get `2015-02-24 22:31:53.04541655 +0100 CET`? Doesn't look at all like the string mentioned in the tests. Is it some kind of local setting?

**Comment by niemeyer** [comment] 2015-02-24 22:24
Sorry, indeed I'll have to fix the test so it runs on a consistent timezone.

Regarding the string format, can you please confirm what version and revision of go-yaml you have locally? This format is time.RFC3339Nano, which is the only possible format coming out of MarshalText, and unrelated to whether you're using time.Now() or not. Hack the test to use that function and you can confirm that the format is still the same.

**Comment by tchap** [comment] 2015-02-24 22:47
Pulled to use the latest `v2`.

Still getting `parsing time "2015-02-24 23:39:59.39193313 +0100 CET" as "2006-01-02T15:04:05Z07:00": cannot parse " 23:39:59.39193313 +0100 CET" as "T"`. The only thing that I am doing is to encode `time.Time` and then read it again...

Looks weird, gonna keep researching...

**Comment by niemeyer** [comment] 2015-02-24 22:48
Can you provide some self-contained sample code that breaks?

**Comment by tchap** [comment] 2015-02-24 22:48
Will try...

**Comment by tchap** [comment] 2015-02-24 23:00
OMG never mind, I am seriously retarded sometimes. The file is generated from a template (`text/template`), which obviously uses `Time.String()` to marshal `time.Time`. Dunno why it's not using `Time.MarshalText`. But I am sorry to waste your time :facepalm:

**Comment by tchap** [comment] 2015-02-24 23:01
That is why I did this hack the other day to make `Time.String` behave like `Time.MarshalText`... Not even sure why these two methods return different representations, though...

**Comment by niemeyer** [comment] 2015-02-24 23:04
No problem. Glad you figured it out.

**Closed as completed by niemeyer** 2015-02-24 23:04 UTC
