### ISSUE TITLE
Embedded structs in targets don't get populated during deserialization

### ISSUE THREAD

**Issue by jackman0** [go-yaml/yaml#169] opened 2016-04-17 17:43 UTC
I discovered that YAML deserialization using this library is not sensitive to embedded structs. Compared to JSON, which deserializes into the embedded struct, the resulting YAML deserialization does not populate the embedded struct. I would expect the YAML deserialization to populate the embedded struct similar to the standard library JSON.

There is a similar ticket (#164), which deals with non-exported embedded structs, but, in this case, everything is exported.

``` go
package main

import (
    "encoding/json"
    "github.com/go-yaml/yaml"
    "log"
    "reflect"
)

type InnerType struct {
    Times struct {
        Speed     int `yaml:"speed" json:"speed"`
        UnitSpeed int `yaml:"unit_speed" json:"unit_speed"`
    } `yaml:"times" json:"times"`

    Resources struct {
        Capacity            Exp `yaml:"capacity" json:"capacity"`
        HidingPlaceCapacity Exp `yaml:"hiding_place_capacity" json:"hiding_place_capacity"`
        Production          Exp `yaml:"production" json:"production"`
    } `yaml:"resources" json:"resources"`
}

type OuterType struct {
    InnerType
    Population Exp `yaml:"population" json:"population"`
}

type Exp struct {
    C float64 `yaml:"c" json:"c"`
    E float64 `yaml:"e" json:"e"`
    K float64 `yaml:"k" json:"k"`
}

var testYAML string = `
times:
  speed: 2
  unit_speed: 3

population:
  c: 204.7
  e: 0.1585

resources:
  production:
    c: 40
    e: 0.153
    k: -60
  capacity:
    c: 850
    e: 0.2125743
    k: 51
`

var testJSON string = `
{
  "times": {
    "speed": 2,
    "unit_speed": 3
  },
  "population": {
    "c": 204.7,
    "e": 0.1585
  },
  "resources": {
    "capacity": {
      "c": 850,
      "e": 0.2125743,
      "k": 51
    },
    "production": {
      "c": 40,
      "e": 0.153,
      "k": -60
    }
  }
}
`

func main() {

    var ot1, ot2 OuterType
    err := yaml.Unmarshal([]byte(testYAML), &ot1)
    if err != nil {
        log.Fatal(err)
    }

    err = json.Unmarshal([]byte(testJSON), &ot2)
    if err != nil {
        log.Fatal(err)
    }

    if !reflect.DeepEqual(ot1, ot2) {
        log.Printf("%v", ot1)
        log.Printf("%v", ot2)
        log.Fatal("The two serialization techniques did not yield the same results!")
    }
}
```

**Comment by jackman0** [comment] 2016-04-17 17:56
FYI, this isn't a problem with the following library:
https://github.com/ghodss/yaml

**Comment by iigorr** [comment] 2016-06-01 13:08
Hi @jackmanlabs,

this is by design (https://github.com/go-yaml/yaml/issues/63). There is the `inline` annotation for that. See docs for annotations https://godoc.org/gopkg.in/yaml.v2

In your example:

``` go
type OuterType struct {
    InnerType `yaml:",inline"`
    Population Exp `yaml:"population" json:"population"`
}
```

**Comment by niemeyer** [comment] 2018-03-26 05:17
Indeed, and this logic was there before json supported the logic it does now. My time machine was broken at the time. :)

I may review this for v3, but at this point there's no guarantee that it will change. It might also become an option. In either case, not an actual bug and the behavior you want is supported, so I'm closing this issue.

**Closed as completed by niemeyer** 2018-03-26 05:17 UTC

**Comment by jackman0** [comment] 2018-03-26 17:47
Thank you. I really appreciate your responsiveness, even if it takes some time. Thank you for devoting so much to the programming world.
